/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vistaSpaceInvasionDani;

import java.awt.event.ActionListener;

/**
 * Clase vista presentacion de mi programa Space Invasion Dani
 * @author Dani Angona
 */
public class NivelSpaceInvasionDani extends javax.swing.JDialog {

    /**
     * Creates new form JDialogSpaceInvasionDani
     */
    public NivelSpaceInvasionDani(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanelLabel = new javax.swing.JPanel();
        jLabelSeleccionaNivelJuego = new javax.swing.JLabel();
        jPanelNiveles = new javax.swing.JPanel();
        jButtonPrincipiante = new javax.swing.JButton();
        jButtonIntermedio = new javax.swing.JButton();
        jButtonAvanzado = new javax.swing.JButton();
        jPanelGuardarNivel = new javax.swing.JPanel();
        jLabelNombreJugador = new javax.swing.JLabel();
        jTextFieldNombreJugador = new javax.swing.JTextField();
        jButtonGuardarNivel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelSeleccionaNivelJuego.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabelSeleccionaNivelJuego.setText("SELECCIONA EL NIVEL DEL JUEGO");
        jPanelLabel.add(jLabelSeleccionaNivelJuego);

        getContentPane().add(jPanelLabel, java.awt.BorderLayout.PAGE_START);

        jPanelNiveles.setLayout(new java.awt.GridBagLayout());

        jButtonPrincipiante.setText("PRINCIPIANTE");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        jPanelNiveles.add(jButtonPrincipiante, gridBagConstraints);

        jButtonIntermedio.setText("INTERMEDIO");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        jPanelNiveles.add(jButtonIntermedio, gridBagConstraints);

        jButtonAvanzado.setText("AVANZADO");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        jPanelNiveles.add(jButtonAvanzado, gridBagConstraints);

        getContentPane().add(jPanelNiveles, java.awt.BorderLayout.CENTER);

        jLabelNombreJugador.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabelNombreJugador.setText("NOMBRE DEL JUGADOR");

        jTextFieldNombreJugador.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jButtonGuardarNivel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButtonGuardarNivel.setText("GUARDAR");

        javax.swing.GroupLayout jPanelGuardarNivelLayout = new javax.swing.GroupLayout(jPanelGuardarNivel);
        jPanelGuardarNivel.setLayout(jPanelGuardarNivelLayout);
        jPanelGuardarNivelLayout.setHorizontalGroup(
            jPanelGuardarNivelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGuardarNivelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabelNombreJugador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jTextFieldNombreJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
            .addGroup(jPanelGuardarNivelLayout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(jButtonGuardarNivel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelGuardarNivelLayout.setVerticalGroup(
            jPanelGuardarNivelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelGuardarNivelLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(jPanelGuardarNivelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombreJugador)
                    .addComponent(jTextFieldNombreJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonGuardarNivel)
                .addGap(16, 16, 16))
        );

        getContentPane().add(jPanelGuardarNivel, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAvanzado;
    private javax.swing.JButton jButtonGuardarNivel;
    private javax.swing.JButton jButtonIntermedio;
    private javax.swing.JButton jButtonPrincipiante;
    private javax.swing.JLabel jLabelNombreJugador;
    private javax.swing.JLabel jLabelSeleccionaNivelJuego;
    private javax.swing.JPanel jPanelGuardarNivel;
    private javax.swing.JPanel jPanelLabel;
    private javax.swing.JPanel jPanelNiveles;
    private javax.swing.JTextField jTextFieldNombreJugador;
    // End of variables declaration//GEN-END:variables

    public void botonPrincipiante(ActionListener l){
        jButtonPrincipiante.addActionListener(l);
    }
    
    public void botonIntermdio(ActionListener l){
        jButtonIntermedio.addActionListener(l);
    }
    
    public void botonAvanzado(ActionListener l){
        jButtonAvanzado.addActionListener(l);
    }
    
    public void guardarNivel(ActionListener l){
        jButtonGuardarNivel.addActionListener(l);
    }
}