/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistaSpaceInvasionDani;

/**
 * Clase vista presentacion de mi programa Space Invasion Dani
 * @author Dani Angona
 */
public class PresentacionSpaceInvasionDani extends javax.swing.JFrame {

    /**
     * Creates new form PresentacionSpaceInvasionDani
     */
    public PresentacionSpaceInvasionDani() {
        initComponents();
        this.setSize(500,300);
        //this.setUndecorated(true);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelSpaceInvasionDani = new javax.swing.JLabel();
        jLabelPorcentajeCarga = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cargando Space Invasion Dani");

        jLabelSpaceInvasionDani.setIcon(new javax.swing.ImageIcon(getClass().getResource("/multimedia/Space_Invasion_Dani.png"))); // NOI18N
        getContentPane().add(jLabelSpaceInvasionDani, java.awt.BorderLayout.CENTER);

        jLabelPorcentajeCarga.setText("0%");
        getContentPane().add(jLabelPorcentajeCarga, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelPorcentajeCarga;
    private javax.swing.JLabel jLabelSpaceInvasionDani;
    // End of variables declaration//GEN-END:variables

    public void setPorcentajeCarga(String texto){
        jLabelPorcentajeCarga.setText(texto);
    }
}